### ISSUE TITLE
process question condition

### ISSUE THREAD

**Issue by k1m0ch1** [eFishery/NeMo#25]
the `condition` key in the `question` is to handle if the question is valid to be asked or not, the question process suppose to be sequentially, so this will be good for custom conditional

conditional using  abbreviation
`eq` as Equal
`gte` Greater Than or Equal
`lte` less than or equal
`lt`  less than
`neq` `not equal`
`in` with the function like in('compare stirng', 'compare string')

coral config must be like this 

```yaml
...
- question:
  slug: third
  asking: some word
  validation:
    rule: *
    message: ""
  condition: first eq 'hello'
...
```

This need to be added on sessions too

if the condition is not meet, the data on sessions must be included but with value null
